### ISSUE TITLE
Error when uploading file

### ISSUE THREAD

**Issue by dausruddin** [UnigramDev/Unigram#1194]
This error popup when uploading a file. Once, a python file was sent in half.
```
System.Reflection.TargetInvocationException: Arg_TargetInvocationException ---> System.NotImplementedException: Arg_NotImplementedException
   at Unigram.Common.UniqueList<System.String,Unigram.Entities.StorageMedia>.IndexOf(Entities.StorageMedia item)
   at Unigram.Controls.CaptionTextBox.Dispatcher_AcceleratorKeyActivated(UI.Core.CoreDispatcher sender, UI.Core.AcceleratorKeyEventArgs args)
   at Unigram!<BaseAddress>+0x184f8ab
   at SharedLibrary!<BaseAddress>+0x4afb04
   at SharedLibrary!<BaseAddress>+0x45eee5
   Exception_EndOfInnerExceptionStack
   at SharedLibrary!<BaseAddress>+0x45f060
   at System.Delegate.DynamicInvoke(Object[] args)
   at Template10.Common.WindowContext.Dispatcher_AcceleratorKeyActivated(UI.Core.CoreDispatcher sender, UI.Core.AcceleratorKeyEventArgs args)
   at Unigram.Controls.RatingBarValueChangedEventHandler.Invoke(Object sender, Controls.RatingBarValueChangedEventArgs e)
   at Unigram!<BaseAddress>+0x1b61ba6
   at Unigram!<BaseAddress>+0x1b62782
   at SharedLibrary!<BaseAddress>+0x4a0ad0
   at Unigram!<BaseAddress>+0x1a414d8
   at Unigram!<BaseAddress>+0x1a41414
   at Microsoft.HockeyApp.Extensibility.Windows.UnhandledExceptionTelemetryModule.CoreApplication_UnhandledErrorDetected(Object sender, ApplicationModel.Core.UnhandledErrorDetectedEventArgs e)
   at System.EventHandler<System.Threading.Tasks.UnobservedTaskExceptionEventArgs>.Invoke(Object sender, Threading.Tasks.UnobservedTaskExceptionEventArgs e)
   at Unigram!<BaseAddress>+0x1b61ba6
   at Unigram!<BaseAddress>+0x1b6235f
```

**Comment by FrayxRulez** [comment]
This is fixed with the new file uploader!
